### PR TITLE
feat: add missing ufw

### LINKED ISSUE #344: Failed to install ufw on Ubuntu 20 LTS
**Describe the bug**
While installing a custom vps server via ssh, installing ufw failed.

**To Reproduce**
1. Create new Server 
2. Fill in The Form
3. Select Ubuntu 20 LTS
4. Webserver nginx Database postgresql 16
5. Press Create Server
6. Wait for the install-ufw step
7. See error

**Expected behavior**
Should install ufw and complete the progress.

**Screenshots**
Screenshot 2024-11-04 at 20 10 56

**Additional context**
I believe `ufw` is not installed by default on Ubuntu 20 LTS, so maybe in the `install-dependencies.sh` we should append `ufw`

### PR DESCRIPTION
**Pull request by eznix86**
resolves #344

### CODE REVIEW

**Comment by eznix86** [comment]
Okay, i'll do another PR for that, what about 1.x because my apps are currently running on 1.x ?

**Comment by joglomedia** [comment]
@eznix86 @saeedvaziry The UFW issue still not fixed in v2.x branch

Affected provider:
AWS EC2 using image Ubuntu 24.04 Minimal

Screen Shot 2024-11-09 at 10 35 07

**Comment by eznix86** [comment]
Will push a PR

**Comment by saeedvaziry** [comment]
no need for a PR. just merged the commit to 2.x as well

**Pull request merged**
