### PR TITLE
show current version

### LINKED ISSUE #140: Indicate Version on Dashboard
I will suggest you show the Vito version on the dashboard or footer of the project: Example: Vito v1.1.0

### PR DESCRIPTION
**Pull request by saeedvaziry**
fix #140

### CODE REVIEW

**Comment by saeedvaziry** [comment]
@saravanasai check this. we can rely on git tags to control versions

**Comment by saeedvaziry** [comment]
Still need to support docker installation

**Comment by saeedvaziry** [comment]
CleanShot 2024-04-01 at 00 02 09@2x
CleanShot 2024-04-01 at 00 02 30@2x

how it will look like on desktop and mobile

**Comment by saeedvaziry** [comment]
CleanShot 2024-04-01 at 00 06 50@2x
show version a bit transparent

**Comment by saravanasai** [comment]
@saeedvaziry   Let me check with this & come back.

**Comment by saravanasai** [comment]
@saeedvaziry  The PR is great. We can go with these changes. Assign me some other task. which I could help you to make this project better.

**Comment by ebenwatts** [comment]
> Still need to support docker installation

I guess wasn't me

**Comment by saeedvaziry** [comment]
@ebenwatts docker already supported.

**Pull request merged**
