### PR TITLE
[2.x] [Filament] Update deprecated `getFormSchema` method to use `form()` override

### PR DESCRIPTION
**Pull request by rtraselbd**
This pull request initiates a partial update for replacing the deprecated `getFormModel` method. This change updates only a few files as a preliminary step. If accepted, further updates will be made to fully replace `getFormModel` across the project.

### Summary of Changes:
- Updated `getFormSchema` to `form()` in selected files to comply with the latest Filament recommendations.
- This partial update serves as an initial implementation to gauge acceptance from the project author.

### Next Steps:
If this pull request is approved, I will proceed to apply similar updates to all existing instances of `getFormSchema` in the project.

### Testing & Verification:
- Verified the functionality of the updated files to ensure compatibility.
- Confirmed that these changes align with Filament's latest standards.

Please review the changes and confirm if this approach is acceptable before proceeding with a full project update.

### CODE REVIEW

**Comment by saeedvaziry** [comment]
@rtraselbd this is being used in some other places as well. do you mind updating those as well in the same PR?

**Comment by rtraselbd** [comment]
@saeedvaziry  Sure, I can take care of updating those as well. I'll make sure to include them in the same PR.

**Comment by saeedvaziry** [comment]
@rtraselbd go ahead please

**Comment by rtraselbd** [comment]
@saeedvaziry I have updated all files.

**Review by saeedvaziry — APPROVED** [review]

**Comment by saeedvaziry** [comment]
Great work!

**Comment by rtraselbd** [comment]
Thank you.

**Pull request merged**
