### PR TITLE
Feature/nodejs

### PR DESCRIPTION
**Pull request by marktopper**
Adding support for installing multiple nodejs versions using nvm.

Screenshots:
image
image
image
image

### CODE REVIEW

**Comment by saeedvaziry** [comment]
@marktopper thanks for the effort on this. VitoDeploy has almost 80% of test coverage and I want to keep it up. So I would appreciate writing tests for the changes you propose before mering it.

**Comment by marktopper** [comment]
> @marktopper thanks for the effort on this. VitoDeploy has almost 80% of test coverage and I want to keep it up. So I would appreciate writing tests for the changes you propose before mering it.

Thanks. Forgot about that. Will write the tests in the morning.

**Comment by marktopper** [comment]
@saeedvaziry thanks for the assistance. I started on the tests and site support, but due to Christmas, I never finished it yet.

Looking forward for more PRs during next year

**Comment by saeedvaziry** [comment]
You did the important part. Thanks for the contribution

**Pull request merged**
