### PR TITLE
fix mixed content error

### PR DESCRIPTION
**Pull request by manusiakemos**
when i deploy on load balancer server it always give me error blocked mixed content. 
so i add config app.scheme to config/app.php to give user an option to force https url.
image

### CODE REVIEW

**Comment by saeedvaziry** [comment]
I don't think this is needed. TrustProxy middleware should already solve the problem.
I will try to reproduce the issue first.

**Comment by manusiakemos** [comment]
> I don't think this is needed. TrustProxy middleware should already solve the problem. I will try to reproduce the issue first.

sorry but in my case it's not enough with only TrustProxy middleware

**Comment by manusiakemos** [comment]
the problem exist if i deploy laravel behind reverse proxy
https://github.com/livewire/livewire/discussions/3084#discussioncomment-8148210

**Comment by saeedvaziry** [comment]
No plans for this at the moment

**Pull request closed without merging**
